places_i_want_to_visit = ['egypt', 'japan', 'mars', 'the galapagos islands', 'kenya', 'singapore', 'hong kong']
print(places_i_want_to_visit)
print()
print(sorted(places_i_want_to_visit))
print(places_i_want_to_visit)
print()
print(sorted(places_i_want_to_visit, reverse=True))
print(places_i_want_to_visit)
print()
places_i_want_to_visit.reverse()
print(places_i_want_to_visit)
places_i_want_to_visit.reverse()
print(places_i_want_to_visit)
print()
places_i_want_to_visit.sort()
print(places_i_want_to_visit)
places_i_want_to_visit.sort(reverse=True)
print(places_i_want_to_visit)
print()
print()
print(f"{places_i_want_to_visit[0].title()} is a very hot place.")
print(f"{places_i_want_to_visit[-1].title()} is the place I want to visit the most.")
faraway_place = places_i_want_to_visit[2].title()
print(faraway_place)
places_i_want_to_visit.append('nepal')
print(places_i_want_to_visit)
places_i_want_to_visit.insert(1, 'france')
print(places_i_want_to_visit)
del places_i_want_to_visit[0]
print(places_i_want_to_visit)
small_country = places_i_want_to_visit.pop()
print(small_country)
print(places_i_want_to_visit)
places_i_want_to_visit.remove('france')
print(places_i_want_to_visit)
print()
print('I have now used every single function I learnt in chapter three!')